version: '3'
services:
  payload:
    image: node:18-alpine
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - payloadnet
  postgres:
    restart: always
    container_name: payloaddb
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: payload
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payloadnet
volumes:
  data:
  pgdata:
  node_modules:
networks:
  payloadnet:
    driver: bridge
